
function(find_files FINDED_FILES DIR)
    set(RESULT)
    foreach(EXTR ${ARGN})
        file(GLOB_RECURSE FILES ${DIR}/${EXTR})
        list(APPEND RESULT ${FILES})
    endforeach()
    set(${FINDED_FILES} ${RESULT} PARENT_SCOPE)
endfunction()

function(find_project_files SRC_FILES DIR)
    set(FILTER *.asm *.nasm *.S *.cpp *.cxx *.cu *.c *.cc *.h *.cuh *.hpp *.qrc *.qss)
    if (UNIX)
        list(APPEND FILTER *.ASM *.NASM *.CPP *.CXX *.CU *.C *.CC *.H *.CUH *.HPP)
    endif()
    if (APPLE)
        list(APPEND FILTER *.mm *.MM *.m *.M)
    endif()
    find_files(FINDED_FILES ${DIR} ${FILTER})
    set(${SRC_FILES} ${FINDED_FILES} PARENT_SCOPE)
endfunction()

function(find_src SRC_FILES DIR)
    set (EXCLUDE_DIR "/test/")
    find_project_files(FINDED_FILES ${DIR})
    foreach (FILE_PATH ${FINDED_FILES})
        string (FIND ${FILE_PATH} ${EXCLUDE_DIR} EXCLUDE_DIR_FOUND)
        if (NOT ${EXCLUDE_DIR_FOUND} EQUAL -1)
            list (REMOVE_ITEM FINDED_FILES ${FILE_PATH})
        endif ()
    endforeach()
    set(${SRC_FILES} ${FINDED_FILES} PARENT_SCOPE)
endfunction()

function(find_test_src SRC_FILES DIR)
    find_project_files(FINDED_FILES ${DIR}/test)
    set(${SRC_FILES} ${FINDED_FILES} PARENT_SCOPE)
endfunction()
