
#ifndef __tt_define_TTNewStandardPushMacro_push_macros__header__
#define __tt_define_TTNewStandardPushMacro_push_macros__header__

#pragma push_macro("TP_ST_RATE_25")
#pragma push_macro("TP_ST_FRAME_RATE_25")
#pragma push_macro("TP_ST_SCALE_25")
#pragma push_macro("TP_ST_RATE_50")
#pragma push_macro("TP_ST_FRAME_RATE_50")
#pragma push_macro("TP_ST_SCALE_50")
#pragma push_macro("TP_ST_RATE_2997")
#pragma push_macro("TP_ST_FRAME_RATE_2997")
#pragma push_macro("TP_ST_SCALE_2997")
#pragma push_macro("TP_ST_RATE_5994")
#pragma push_macro("TP_ST_FRAME_RATE_5994")
#pragma push_macro("TP_ST_SCALE_5994")
#pragma push_macro("TP_ST_RATE_60")
#pragma push_macro("TP_ST_FRAME_RATE_60")
#pragma push_macro("TP_ST_SCALE_60")
#pragma push_macro("TP_ST_RATE_30")
#pragma push_macro("TP_ST_FRAME_RATE_30")
#pragma push_macro("TP_ST_SCALE_30")
#pragma push_macro("TP_ST_RATE_24")
#pragma push_macro("TP_ST_FRAME_RATE_24")
#pragma push_macro("TP_ST_SCALE_24")
#pragma push_macro("TP_ST_RATE_2398")
#pragma push_macro("TP_ST_FRAME_RATE_2398")
#pragma push_macro("TP_ST_SCALE_2398")

#pragma push_macro("TP_ST_RATE_22")
#pragma push_macro("TP_ST_FRAME_RATE_22")
#pragma push_macro("TP_ST_SCALE_22")

#pragma push_macro("TP_ST_RATE_21")
#pragma push_macro("TP_ST_FRAME_RATE_21")
#pragma push_macro("TP_ST_SCALE_21")

#pragma push_macro("TP_ST_RATE_20")
#pragma push_macro("TP_ST_FRAME_RATE_20")
#pragma push_macro("TP_ST_SCALE_20")

#pragma push_macro("TP_ST_RATE_19")
#pragma push_macro("TP_ST_FRAME_RATE_19")
#pragma push_macro("TP_ST_SCALE_19")

#pragma push_macro("TP_ST_RATE_18")
#pragma push_macro("TP_ST_FRAME_RATE_18")
#pragma push_macro("TP_ST_SCALE_18")

#pragma push_macro("TP_ST_RATE_17")
#pragma push_macro("TP_ST_FRAME_RATE_17")
#pragma push_macro("TP_ST_SCALE_17")

#pragma push_macro("TP_ST_RATE_16")
#pragma push_macro("TP_ST_FRAME_RATE_16")
#pragma push_macro("TP_ST_SCALE_16")

#pragma push_macro("TP_ST_RATE_15")
#pragma push_macro("TP_ST_FRAME_RATE_15")
#pragma push_macro("TP_ST_SCALE_15")

#pragma push_macro("FRAMES_SECOND_25")
#pragma push_macro("FRAMES_MINUTE_25")
#pragma push_macro("FRAMES_HOUR_25")

#pragma push_macro("FRAMES_SECOND_24")
#pragma push_macro("FRAMES_MINUTE_24")
#pragma push_macro("FRAMES_HOUR_24")
#pragma push_macro("FRAMES_SECOND_NODROP_30")
#pragma push_macro("FRAMES_MINUTE_NODROP_30")
#pragma push_macro("FRAMES_HOUR_NODROP_30")
#pragma push_macro("FRAMES_MINUTE_30_DROP")
#pragma push_macro("FRAMES_10MINUTES_30_DROP")
#pragma push_macro("FRAMES_HOUR_30_DROP")
#pragma push_macro("FRAMES_SECOND_50")
#pragma push_macro("FRAMES_MINUTE_50")
#pragma push_macro("FRAMES_HOUR_50")
#pragma push_macro("TP_WIDTH_NUM")
#pragma push_macro("TP_HEIGHT_NUM")
#pragma push_macro("TP_FRAMERATE_NUM")
#pragma push_macro("TP_VIEW_NUM")
#pragma push_macro("TP_BITCOUNT_NUM")
#pragma push_macro("TP_VIDEOSTANDARD_NUM")
#pragma push_macro("TPVS_Unknown")

#pragma push_macro("TPVS_VERSION")
#pragma push_macro("TPVS_FRAMERATE_I")
#pragma push_macro("TPVS_DAR_I")
#pragma push_macro("TPVS_VIEW_I")
#pragma push_macro("TPVS_WIDTH_I")
#pragma push_macro("TPVS_HEIGHT_I")
#pragma push_macro("TPVS_BITCOUNT_I")
#pragma push_macro("TPVS_SET_VERSION")
#pragma push_macro("TPVS_SET_FRAMERATE")
#pragma push_macro("TPVS_SET_DAR")
#pragma push_macro("TPVS_SET_VIEW")
#pragma push_macro("TPVS_SET_WIDTH")
#pragma push_macro("TPVS_SET_HEIGHT")
#pragma push_macro("TPVS_SET_BITCOUNT")
#pragma push_macro("TP_EXSIT_VIDEOSTANDARD_NUM")

#undef TP_ST_RATE_25
#undef TP_ST_FRAME_RATE_25
#undef TP_ST_SCALE_25
#undef TP_ST_RATE_50
#undef TP_ST_FRAME_RATE_50
#undef TP_ST_SCALE_50
#undef TP_ST_RATE_2997
#undef TP_ST_FRAME_RATE_2997
#undef TP_ST_SCALE_2997
#undef TP_ST_RATE_5994
#undef TP_ST_FRAME_RATE_5994
#undef TP_ST_SCALE_5994
#undef TP_ST_RATE_60
#undef TP_ST_FRAME_RATE_60
#undef TP_ST_SCALE_60
#undef TP_ST_RATE_30
#undef TP_ST_FRAME_RATE_30
#undef TP_ST_SCALE_30
#undef TP_ST_RATE_24
#undef TP_ST_FRAME_RATE_24
#undef TP_ST_SCALE_24
#undef TP_ST_RATE_2398
#undef TP_ST_FRAME_RATE_2398
#undef TP_ST_SCALE_2398
#undef TP_ST_RATE_22
#undef TP_ST_FRAME_RATE_22
#undef TP_ST_SCALE_22
#undef TP_ST_RATE_21
#undef TP_ST_FRAME_RATE_21
#undef TP_ST_SCALE_21
#undef TP_ST_RATE_20
#undef TP_ST_FRAME_RATE_20
#undef TP_ST_SCALE_20
#undef TP_ST_RATE_19
#undef TP_ST_FRAME_RATE_19
#undef TP_ST_SCALE_19
#undef TP_ST_RATE_18
#undef TP_ST_FRAME_RATE_18
#undef TP_ST_SCALE_18
#undef TP_ST_RATE_17
#undef TP_ST_FRAME_RATE_17
#undef TP_ST_SCALE_17
#undef TP_ST_RATE_16
#undef TP_ST_FRAME_RATE_16
#undef TP_ST_SCALE_16
#undef TP_ST_RATE_15
#undef TP_ST_FRAME_RATE_15
#undef TP_ST_SCALE_15
#undef FRAMES_SECOND_25
#undef FRAMES_MINUTE_25
#undef FRAMES_HOUR_25
#undef FRAMES_SECOND_24
#undef FRAMES_MINUTE_24
#undef FRAMES_HOUR_24
#undef FRAMES_SECOND_NODROP_30
#undef FRAMES_MINUTE_NODROP_30
#undef FRAMES_HOUR_NODROP_30
#undef FRAMES_MINUTE_30_DROP
#undef FRAMES_10MINUTES_30_DROP
#undef FRAMES_HOUR_30_DROP
#undef FRAMES_SECOND_50
#undef FRAMES_MINUTE_50
#undef FRAMES_HOUR_50
#undef TP_WIDTH_NUM
#undef TP_HEIGHT_NUM
#undef TP_FRAMERATE_NUM
#undef TP_VIEW_NUM
#undef TP_BITCOUNT_NUM
#undef TP_VIDEOSTANDARD_NUM
#undef TPVS_Unknown
#undef TPVS_VERSION
#undef TPVS_FRAMERATE_I
#undef TPVS_DAR_I
#undef TPVS_VIEW_I
#undef TPVS_WIDTH_I
#undef TPVS_HEIGHT_I
#undef TPVS_BITCOUNT_I
#undef TPVS_SET_VERSION
#undef TPVS_SET_FRAMERATE
#undef TPVS_SET_DAR
#undef TPVS_SET_VIEW
#undef TPVS_SET_WIDTH
#undef TPVS_SET_HEIGHT
#undef TPVS_SET_BITCOUNT
#undef TP_EXSIT_VIDEOSTANDARD_NUM

#endif
